# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1a\n\x0cScoreRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\rScoreResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x32\x63\n\x0eStudentService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12)\n\x08getScore\x12\r.ScoreRequest\x1a\x0e.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=15
  _globals['_LOGINREQUEST']._serialized_end=65
  _globals['_LOGINRESPONSE']._serialized_start=67
  _globals['_LOGINRESPONSE']._serialized_end=97
  _globals['_SCOREREQUEST']._serialized_start=99
  _globals['_SCOREREQUEST']._serialized_end=125
  _globals['_SCORERESPONSE']._serialized_start=127
  _globals['_SCORERESPONSE']._serialized_end=183
  _globals['_STUDENTSERVICE']._serialized_start=185
  _globals['_STUDENTSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
