# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: active.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'active.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tive.proto\"\x07\n\x05\x45mpty\"\"\n\rStateResponse\x12\x11\n\tis_active\x18\x01 \x01(\x08\x32X\n\x0cStateService\x12$\n\nDeactivate\x12\x06.Empty\x1a\x0e.StateResponse\x12\"\n\x08GetState\x12\x06.Empty\x1a\x0e.StateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'active_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_STATERESPONSE']._serialized_start=25
  _globals['_STATERESPONSE']._serialized_end=59
  _globals['_STATESERVICE']._serialized_start=61
  _globals['_STATESERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
