

services:
  user_service:
    build: ./user_services
    ports:
      - "5000:5000"
  
  order_service:
    build: ./order_services
    ports:
      - "5001:5001"
    depends_on:
      - user_service