# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'student.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07student\"\x1d\n\x0estudentRequest\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\"8\n\x0fstudentResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x32S\n\x0eStudentService\x12\x41\n\ngetStudent\x12\x17.student.studentRequest\x1a\x18.student.studentResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTREQUEST']._serialized_start=26
  _globals['_STUDENTREQUEST']._serialized_end=55
  _globals['_STUDENTRESPONSE']._serialized_start=57
  _globals['_STUDENTRESPONSE']._serialized_end=113
  _globals['_STUDENTSERVICE']._serialized_start=115
  _globals['_STUDENTSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
